import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { CreditCard, ArrowLeft, ShieldCheck, Clock3 } from "lucide-react";
import { getPlayerDashboardPath } from "@/lib/walletNavigation";
import { useLocation } from "wouter";

export default function AddMoneyPage() {
  const [, setLocation] = useLocation();
  return <div className="min-h-screen bg-background pb-20"><div className="border-b border-primary/20 bg-gradient-gaming px-4 py-6"><div className="mx-auto max-w-2xl"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><CreditCard className="h-8 w-8 text-accent" /><h1 className="text-3xl font-bold text-accent">Add Money</h1></div><Button type="button" variant="outline" size="sm" className="border-primary/50 bg-background/40 text-foreground hover:border-primary hover:bg-primary/10" onClick={() => setLocation(getPlayerDashboardPath())}><ArrowLeft className="mr-1 h-4 w-4" />Dashboard</Button></div><p className="mt-2 text-muted-foreground">Secure wallet deposits through our upcoming payment gateway.</p></div></div><main className="mx-auto max-w-2xl px-4 py-8"><Card className="card-gaming overflow-hidden border-accent/35"><div className="border-b border-accent/20 bg-accent/5 p-5"><Badge className="border-accent/35 bg-accent/15 text-accent">PAYMENT GATEWAY · SETUP PENDING</Badge><h2 className="mt-4 text-2xl font-black text-foreground">Secure checkout is coming soon</h2><p className="mt-2 max-w-xl text-sm leading-relaxed text-muted-foreground">Razorpay order creation, payment verification, and webhook-based wallet settlement are prepared on the server. Live checkout will activate only after the owner provides merchant credentials.</p></div><div className="space-y-4 p-5"><div className="flex items-start gap-3 rounded-lg border border-primary/20 bg-primary/5 p-4"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><div><p className="font-bold">No payment is accepted yet</p><p className="mt-1 text-sm text-muted-foreground">For your safety, this page will not collect deposit details or open an incomplete checkout until setup is complete.</p></div></div><div className="flex items-start gap-3 rounded-lg border border-muted bg-muted/20 p-4"><Clock3 className="mt-0.5 h-5 w-5 shrink-0 text-muted-foreground" /><div><p className="font-bold">What will happen after activation</p><p className="mt-1 text-sm text-muted-foreground">You will select an amount, complete the official gateway checkout, and receive Deposit Balance credit only after verified payment confirmation.</p></div></div><Button className="w-full" variant="outline" onClick={() => setLocation(getPlayerDashboardPath())}>Return to Player App</Button></div></Card></main></div>;
}
