import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";

export function FinalFeatureManagement() {
  const utils = trpc.useUtils(); const [message, setMessage] = useState("");
  const announcements = trpc.admin.announcements.useQuery(); const proofs = trpc.admin.resultProofs.useQuery();
  const create = trpc.admin.createAnnouncement.useMutation({ onSuccess: () => { setMessage(""); utils.admin.announcements.invalidate(); utils.announcements.live.invalidate(); toast.success("Announcement published."); }, onError: (e) => toast.error(e.message) });
  const update = trpc.admin.updateAnnouncement.useMutation({ onSuccess: () => { utils.admin.announcements.invalidate(); utils.announcements.live.invalidate(); }, onError: (e) => toast.error(e.message) });
  const review = trpc.admin.reviewResultProof.useMutation({ onSuccess: () => { utils.admin.resultProofs.invalidate(); toast.success("Proof review saved."); }, onError: (e) => toast.error(e.message) });
  return <div className="space-y-6"><Card className="card-gaming"><h2 className="font-bold text-accent">Live Announcement Ticker</h2><p className="mt-1 text-sm text-muted-foreground">Messages appear on the Player Home screen immediately.</p><div className="mt-4 flex gap-2"><Input className="input-gaming" value={message} maxLength={240} placeholder="Example: BR Per Kill Special opens at 8 PM" onChange={(e) => setMessage(e.target.value)} /><Button className="btn-neon" disabled={!message.trim() || create.isPending} onClick={() => create.mutate({ message, isActive: true })}>Publish</Button></div><div className="mt-4 space-y-2">{announcements.data?.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 rounded-lg border border-primary/20 p-3"><p className="min-w-0 break-words text-sm">{item.message}</p><Button size="sm" variant="outline" onClick={() => update.mutate({ id: item.id, message: item.message, isActive: !item.isActive })}>{item.isActive ? "Disable" : "Enable"}</Button></div>)}</div></Card><Card className="card-gaming"><h2 className="font-bold text-accent">Match Result Proof Review</h2><p className="mt-1 text-sm text-muted-foreground">Approve or reject player-uploaded victory screenshots.</p><div className="mt-4 space-y-3">{proofs.data?.length ? proofs.data.map(({ proof, matchTitle, playerName }) => <div key={proof.id} className="rounded-lg border border-primary/20 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold">{playerName} · {matchTitle}</p><Badge>{proof.status}</Badge></div><a className="mt-2 block text-sm text-primary underline" href={proof.imageUrl} target="_blank" rel="noreferrer">Open screenshot proof</a>{proof.playerNote ? <p className="mt-2 text-sm text-muted-foreground">{proof.playerNote}</p> : null}{proof.status === "pending" && <div className="mt-3 flex gap-2"><Button size="sm" className="btn-neon" onClick={() => review.mutate({ proofId: proof.id, status: "approved" })}>Approve</Button><Button size="sm" variant="outline" onClick={() => review.mutate({ proofId: proof.id, status: "rejected" })}>Reject</Button></div>}</div>) : <p className="text-sm text-muted-foreground">No proof submissions yet.</p>}</div></Card></div>;
}
